name: Deploy to server

on:
  workflow_run:
    workflows: [Release Image]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: updating docker image on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd goshne
            docker compose pull app && docker compose up -d
            sleep 10
            docker compose exec app php artisan migrate --force
